### ISSUE TITLE
https://charmhub.io/redis-k8s?channel=edge returns a 500 error code

### ISSUE THREAD

**Issue by cmisare-canonical** [canonical-web-and-design/charmhub.io#1012]
When visiting https://charmhub.io/redis-k8s?channel=edge in an incognito window (there seems to be some caching that displays an old revision 8 of the page instead), a 500 error page is shown. This seems to be the case for any subpage (docs, libraries, etc) when specifying the edge channel as well.

There is no error when visiting the stable channel page.

![edge](https://user-images.githubusercontent.com/84032480/118524074-ff864180-b6fa-11eb-8c53-4b553fee283b.png)

**Comment by jkfran** [comment]
The issue has been solved however the URL you are using for docs in the metadata.yaml is invalid:
https://github.com/cmisare-canonical/redis-operator/blob/2262b188dfb264c7eb1f991782990fab94698a95/metadata.yaml#L18

We require the full URL with the slug, so in this case, it should be: https://discourse.charmhub.io/t/redis-docs-index/4571

**Comment by cmisare-canonical** [comment]
That makes sense, I didn't realize the formatting of the link was important and had shortened it to just the ID in case the title ever changed. I'll update it to be better formatted, thank you for following up.
