### ISSUE TITLE
Indicate a charms subordinate status in the UI

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/charmhub.io#1015]
It would be nice if the charm's details page would indicate if it's a subordinate or not.

ex) https://charmhub.io/nrpe

**Comment by danielmutis** [comment]
@hatched do you know if this is something that was shown in the previous store? If not, do you have any idea of why that is?

**Comment by hatched** [comment]
It wasn't, probably because nobody thought of it :)

Subordinate charms operate quite a bit differently than normal ones so it would be best to indicate as such somewhere in the UI.

**Comment by danielmutis** [comment]
Okay, thanks. I see that there is a field in the metadata.yaml which says whether it's subordinate or not. It would be interesting to explore flagging this information in the detail pages.

**Comment by jkfran** [comment]
@Roadmaster Do you know if this field should be on the API? Looks like we could get it from the metadata.yaml for now.

**Comment by Roadmaster** [comment]
metadata is probably the right place to get it, we don't expose that as a top-level field.

**Comment by heitorPB** [comment]
`juju info` shows if the charm is subordinate or not:
```bash
$ juju info ntp
name: ntp
charm-id: SLOkZHn8HVy160M2oJdvXatzlu7ZBEVx
summary: Network Time Protocol
publisher: NTP charm developers
supports: bionic, xenial, trusty, focal
subordinate: true
store-url: https://charmhub.io/ntp
[...]
```

**Comment by jkfran** [comment]
I am going to leave here the comment as well, @Roadmaster mentioned that this could be a field on the info endpoint, here is the request:
https://bugs.launchpad.net/snapstore-server/+bug/1960423

**Comment by Lukewh** [comment]
This is now ready to implement.
