### ISSUE TITLE
Display name not updated

### ISSUE THREAD

**Issue by sajoupa** [canonical-web-and-design/charmhub.io#1032]
I changed the display name for https://charmhub.io/telegraf-k8s, but it is still displaying the old value (it's displaying 'Telegraf', I changed it to 'Telegraf k8s').
Is there something specific that needs to be done ?
Not sure if it's a direct consequence, but a search for 'telegraf-k8s' in charmhub.io also yields 0 results.

**Comment by jkfran** [comment]
I created the following bug on Launchpad:
https://bugs.launchpad.net/snapstore-server/+bug/1930848
