### ISSUE TITLE
What relations are supported by each charm?

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/charmhub.io#1049]
When viewing a charm there doesn't appear to be a way to know what relations are supported and what that charm can relate to.

I understand that there is a design which includes a list of charms that you can relate to but this doesn't cover the issue of ambiguous relationships. If I can relate something on multiple endpoints I need to know what those endpoints are. Without the ability to actually view the relation metadata I'm not sure of a way around this. And because there doesn't appear to be a way to view a charm's source or a way to download it this will need to be handled in the UI somewhere. 

When writing a charm that is to relate to an existing one I also need to know what endpoints it currently supports so that I can write a new charm accordingly. Being able to audit the charms source code is also a requirement for this.

**Comment by danielmutis** [comment]
@hatched The design that we have for displaying relations on Charmhub is not only a [list of charms](https://zpl.io/bAryxKq), but if you click further into one of the charms listed you would be able to see [all the endpoints that are available](https://zpl.io/VDeZ84e) to connect as well. 

These designs have already been implemented in the front end and we are waiting for APIs to be able to display this information.

**Comment by hatched** [comment]
Thanks for the links @danielmutis . What you'll notice though is that this tells me what endpoints are used when relating between two applications. It doesn't tell me what endpoints are available on the charm.

**Comment by cristinadresch** [comment]
Waiting on API

**Comment by anasereijo** [comment]
The [UX work for a new Integrations tab](https://app.zenhub.com/workspaces/-marketplace-tribe-593688b45aa7c527b96f9401/issues/canonical-web-and-design/marketplace-tribe/2243) on charmhub.io is now completed. You can see the wireframes on [Zeplin](https://app.zeplin.io/project/61f0185764e363a52fb01377?seid=62349a2988510d97b0efdf3a).

The [visual work and implementation](https://app.zenhub.com/workspaces/-marketplace-tribe-593688b45aa7c527b96f9401/issues/canonical-web-and-design/marketplace-tribe/2553) are planned for this cycle (22.10). We are also waiting for the store APIs to be ready.
