### ISSUE TITLE
Add revision to channels dropdown

### ISSUE THREAD

**Issue by jkfran** [canonical-web-and-design/charmhub.io#1051]
In the channels dropdown, we should add an extra column for the revision.

![image](https://user-images.githubusercontent.com/6353928/122240906-06e76900-ceba-11eb-9b12-107d6ae945f8.png)

**Comment by danielmutis** [comment]
I think it would be good if the revision column comes after the version one. Version still seems a bit more relevant for charm consumers.

**Comment by heitorPB** [comment]
This is related to #1070 , to add a column for the release date :)
