### ISSUE TITLE
Add to new model option is not found

### ISSUE THREAD

**Issue by RatiRanjanDas** [canonical-web-and-design/charmhub.io#1053]
"Add to new model" option is not found with charms. How can I get that for testing purpose

**Comment by RatiRanjanDas** [comment]
In juju gui interface... I am not getting "Add to new model" option for testing purpose.

**Comment by hatched** [comment]
Hi @RatiRanjanDas With the change to the new charmhub and Juju Dashboard that functionality was removed for the time being. For now you'll have to deploy charms and bundles via the CLI using the command outlined in the charm details page header.

**Comment by RatiRanjanDas** [comment]
Hi@hatched Now issue is that if anyone who is new to this concept then it will be very difficult for him/her to bulid relations between two charms components. Is there any solutions for that..
