### ISSUE TITLE
Hi@hatched Now issue is that if anyone who is new to this concept then it will be very difficult for him/her to bulid relations between two charms components. Is there any solutions for that..

### ISSUE THREAD

**Issue by RatiRanjanDas** [canonical-web-and-design/charmhub.io#1054]
Hi@hatched Now issue is that if anyone who is new to this concept then it will be very difficult for him/her to bulid relations between two charms components. Is there any solutions for that..

_Originally posted by @RatiRanjanDas in https://github.com/canonical-web-and-design/charmhub.io/issues/1053#issuecomment-865553667_

**Comment by hatched** [comment]
I can totally appreciate that it can be more challenging to understand the concepts without the easy drag & drop support. In the near future the charmhub team will be adding support for displaying relations on the charm details page which will help alleviate some of this onboarding issue. Adding drag and drop support to the new Juju dashboard is not currently on our roadmap but I can make note of your interest in it for prioritization.

**Comment by hatched** [comment]
For now you can view the charms on https://jaas.ai/ to see what relations are supported.
