### ISSUE TITLE
Cannot embbed charm card in HTML

### ISSUE THREAD

**Issue by heitorPB** [canonical-web-and-design/charmhub.io#1075]
Hello,

I am trying to add the `Embeddable cards` from https://charmhub.io/slurmd/publicise/cards into our [custom documentation page](https://omnivector-solutions.github.io/osd-documentation/master/configuration/slurmd.html), but I receive and error when browsing the page:

![slurmd-card](https://user-images.githubusercontent.com/13461702/125476554-43235b01-72fd-492e-bc06-dc8aec7844f3.png)

I added the card using the HTML as shown in Charmhub:

```HTML
<iframe src="https://charmhub.io/slurmd/embedded?button=white&channels=true&summary=true&base=true" frameborder="0" width="100%" height="470px" style="border: 1px solid #CCC; border-radius: 2px;"></iframe>
```

Here is a MWE to reproduce this error:

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>MWE</title>
	</head>
	<body>
		<iframe src="https://charmhub.io/slurmd/embedded?button=white&channels=true&summary=true&base=true" frameborder="0" width="100%" height="470px" style="border: 1px solid #CCC; border-radius: 2px;"></iframe>
	</body>
</html>
```

**Comment by Lukewh** [comment]
Is this still an issue, I just modified the page in browser, and it seemed to work as expected?
![image.png](https://images.zenhubusercontent.com/59316f3551aa2c3057803f4b/f557a7ba-16d7-43dd-aa11-821c145f77d6)?

**Comment by heitorPB** [comment]
Sweet! And also the MWE now works also.

Do you know if there was any change on CharmHub side?

**Comment by Lukewh** [comment]
The internal module we use for flask apps is constantly updated so at some point the security policy for embedding those pages was relaxed :)!
Closing this issue, please reopen if you still have problems. Thanks for the report!
