### ISSUE TITLE
There is no "Relations" tab for a charm

### ISSUE THREAD

**Issue by mhilton** [canonical-web-and-design/charmhub.io#1098]
When displaying the details of a charm there are tabs for "Resources", "Configure" and "Actions", but there is no equivalent for "Relations". As relations are an important part of what makes charms useful it seems quite important to expose that information.

**Comment by danielmutis** [comment]
@mhilton thanks for raising this issue. We are aware that relations are a key part of Charmhub and we have worked on designs to display this in the website. At the moment we still don't have APIs to be able to implement those designs, and we expect to be able to do this at the end of this cycle. I am closing this issue as it's related to [1049](https://github.com/canonical-web-and-design/charmhub.io/issues/1049).
