### ISSUE TITLE
Display charm's license in charmhub

### ISSUE THREAD

**Issue by heitorPB** [canonical-web-and-design/charmhub.io#1100]
Charms generally have a `LICENSE` file in them. CHarmhub should be able to identify what license is used and display that. It would be awesome to also link to a page with description of that license, for example [Choose a License/MIT](https://choosealicense.com/licenses/mit/).

GitHub does something similar, if you browse a repository it shows the license and have a link to a page, see bottom right part of this screenshot:
![github-license](https://user-images.githubusercontent.com/13461702/128183318-4bc63557-22b6-412a-8cdc-0000e7cfee84.png)

**Comment by jkfran** [comment]
Related with https://discourse.charmhub.io/t/juju-should-know-about-charm-licenses/4984

**Comment by jkfran** [comment]
Both APIs are not ready for it, we should wait until they are

**Comment by heitorPB** [comment]
What does it mean to close this issue? CharmHub will not display the charm license? Or it is something not planned to be done soon?

**Comment by cristinadresch** [comment]
@heitorPB we have dependencies on the API for this, I know that Sergio closed the issue on the charmcraft API too so the best place to discuss this now in [on discourse](https://discourse.charmhub.io/t/juju-should-know-about-charm-licenses/4984). It's super complex so we are not expecting to have this done in the API in the next 6 months, so just closing it for now.

**Comment by heitorPB** [comment]
Hi @cristinadresch. Thanks for the clarification!
