### ISSUE TITLE
Search does not contain bundles

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/charmhub.io#1103]
A common thing a user will what to do is search for bundles as a full solution. When [searching](https://charmhub.io/?q=openstack) for [this bundle](https://charmhub.io/openstack-base) it does not appear in the results. This means a lot of people are still using jaas.ai for this information.

**Comment by jkfran** [comment]
Hi @anthonydillon ,

I can see bundles on that search, there is one on the second row and a few more in the following ones. The search order doesn't seem to be by relevance, looks like it's alphabetical and that means we are overriding the original order returned by the API.

IMO we should just fix the order.

**Comment by hatched** [comment]
This is interesting as yesterday there definitely weren't any bundles in that search result. Maybe some design work also needs to be done to make bundles stand out a bit more, especially when the bundle icons are all grey it's hard to see.

![Screen Shot 2021-08-09 at 9 02 59 AM](https://user-images.githubusercontent.com/532033/128728330-36c5056f-f6c0-4534-9e34-b358c1fe4b21.png)

**Comment by jkfran** [comment]
We can close this issue now. Thank you.
