### ISSUE TITLE
Add opensearch

### ISSUE THREAD

**Issue by sed-i** [canonical-web-and-design/charmhub.io#1121]
It would be really nice to have the option to search for charms directly from the address bar like so: `ch nginx`

![Screenshot from 2021-09-08 16-50-39](https://user-images.githubusercontent.com/82407168/132584083-fa42e319-bad0-4d82-8e9e-5825bf27a00d.png)

**Comment by cristinadresch** [comment]
Thanks for taking the time to send this. We will consider this feature in the future.
