### ISSUE TITLE
markdown in docstrings is not rendered for library docs

### ISSUE THREAD

**Issue by sed-i** [canonical-web-and-design/charmhub.io#1127]
markdown inside module docstring is rendered (specifically the backticks):
https://charmhub.io/alertmanager-k8s/libraries/alertmanager_dispatch

but markdown (specifically the backticks) in the class/method docstrings is not rendered.
https://charmhub.io/alertmanager-k8s/libraries/alertmanager_dispatch#alertmanagerconsumer

![libdocmd](https://user-images.githubusercontent.com/82407168/133366033-08b99267-5fb2-42b8-ae28-4466392f41f6.png)

**Comment by steverydz** [comment]
Thanks for raising this bug. We will look into it.

**Comment by jkfran** [comment]
At the moment we don't support Markdown in the Class/methods docstrings, we only support the header of the file:
https://juju.is/tutorials/document-your-library#1-introduction

**Comment by sed-i** [comment]
Thanks for clarifying.
But why close the issue? Is this a "won't fix"?

**Comment by jkfran** [comment]
We just had a meeting reviewing issues and we agreed on not supporting it as this was the original plan. So, yes it is a "won't fix" however, this is open to discussion in the future and if this request gets enough support we will take a look into it.
