### ISSUE TITLE
switching between channel and library docs is buggy

### ISSUE THREAD

**Issue by sed-i** [canonical-web-and-design/charmhub.io#1128]
While clicking around in the [alertmanager page](https://charmhub.io/alertmanager-k8s) I discovered the following bugs:
1. going from [main page](https://charmhub.io/alertmanager-k8s) to [Libraries](https://charmhub.io/alertmanager-k8s/libraries) to [alertmanager_dispatch](https://charmhub.io/alertmanager-k8s/libraries/alertmanager_dispatch) breaks the channel drop down: now it only has "Stable 1". After clicking back on "Introduction" the dropdown works again.
2. main page -> choose "latest/edge" from channel dropdown -> Libraries, then "Edge 6" is shown in the dropdown, but as soon as I click "alertmanager_dispatch", the dropdown channel changes to Stable 1 and it again becomes the only option (Edge is not there anymore).

![libdocbuggy](https://user-images.githubusercontent.com/82407168/133367390-08fd9c39-2f58-4be0-a668-f4a98cbf6137.png)

**Comment by steverydz** [comment]
Thanks for raising this. We will look into it.
