### ISSUE TITLE
Fluentbit charm not "searchable" in charmhub

### ISSUE THREAD

**Issue by heitorPB** [canonical-web-and-design/charmhub.io#1147]
Hello,

Our newest charm, [Fluentbit](https://charmhub.io/fluentbit), is published in CharmHub, but we cannot find it when searching for `fluentbit` or `Fluentbit`.

Is there some other step we need to take for our charms appear in the search page?

**Comment by Roadmaster** [comment]
I set the "listed" flag to "true", it should show as soon as you publish something new to the stable channel.

**Comment by Roadmaster** [comment]
yes, newly-registered charms are unlisted by default, so you do have to ask, for the time being, for a store operator to flip the listed bit. Probably easier to do it in the discourse forum and @ me (@roadmr in the forum).

- Daniel

**Comment by heitorPB** [comment]
Oh, good to know that. Thanks for the help!
