### ISSUE TITLE
listing page is missing a link to navigate back to the charm page

### ISSUE THREAD

**Issue by sed-i** [canonical-web-and-design/charmhub.io#1148]
It would be handy if the listing page included a link for navigating back to the charm page.

At the moment there is only a link to "my charms and bundles" and the only way to go back to the charm page is by removing the "listing" suffix from the URL.

![Screenshot from 2021-09-29 10-39-04](https://user-images.githubusercontent.com/82407168/135291276-6181c33c-cfc9-4e97-884d-4048ca9da4a5.png)

**Comment by AnnSoMuller** [comment]
add link to the name or align with snapcraft.io
![Image Pasted at 2021-11-5 14-18.png](https://images.zenhubusercontent.com/606c1e6c5aab87d8cd196107/d97387f6-436d-4f74-8211-e19b2d796944)
keep consistensy in mind and create issue for snapcraft.io if needed
