### ISSUE TITLE
Library icons showing through the tooltip popup

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/charmhub.io#1149]
https://charmhub.io/prometheus-k8s/libraries/prometheus_scrape

<img width="911" alt="Screen Shot 2021-10-06 at 2 26 27 PM" src="https://user-images.githubusercontent.com/532033/136278065-09ae5543-c247-417d-8ff9-81ec5f2b392c.png">

**Comment by steverydz** [comment]
No longer an issue as this was removed in https://github.com/canonical-web-and-design/charmhub.io/commit/a646671c77e2b417cf4ab15ff4b3c338ee62121d#diff-40da8801c467e66a3c6492f514a3750865f18a2399cb923365f7e7baf7bb93e8
