### ISSUE TITLE
Not Rendering 'nextcloud' documents correctly

### ISSUE THREAD

**Issue by jameinel** [canonical-web-and-design/charmhub.io#1152]
If you go to:
https://charmhub.io/nextcloud/docs

There is a discrepancy about what docs are visible.
In my normal browser, I see the table of contents, but when visiting one of the entries, the actual content of the page says "nothing to see here"
![Image Pasted at 2021-10-7 09-48](https://user-images.githubusercontent.com/202877/136406831-b0c0f248-bcdd-45a6-87cf-5196ec731de9.png)

However, when I visit on a Private browsing, I don't see anything:
![Image Pasted at 2021-10-7 09-47](https://user-images.githubusercontent.com/202877/136406997-264ad491-f244-487a-9c92-b21ad0f24e8d.png)

note that the charm does have a proper ToC page:
https://discourse.charmhub.io/t/nextcloud-docs-index/4591

**Comment by jkfran** [comment]
I replied on mattermost, basically the docs are missing in the latest release of the metadata.yaml. We have different cache nodes and that explains your issue.
