### ISSUE TITLE
Viewing libraries locally causes error

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/charmhub.io#1158]
After running this site locally using `dotrun`
When you visit http://0.0.0.0:8045/loki-k8s/libraries/loki_push_api
You get an error like this:
```
SyntaxError
File "<unknown>", line 543
    if bind_address := self.charm.model.get_binding(self._relation_name).network.bind_address:
                     ^
SyntaxError: invalid syntax
```
Which is caused by dotrun using Python 3.4 and the walrus operator implemented on Python 3.8.

**Comment by jkfran** [comment]
This one should be solved with https://github.com/canonical-web-and-design/dotrun/pull/64
