### ISSUE TITLE
Bundles - config tab 'no configuration' state 

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/charmhub.io#1163]
Fran implemented the new config tab on bundles. But some charms dont have configuration avaialble, see below:

https://staging.charmhub.io/kubeflow/configure/admission-webhook

We need a clearer way to display no configuration, as now it looks like the bundle might not have a config?![Screenshot 2021-10-22 at 10.14.40.png](https://images.zenhubusercontent.com/5c73e557b33938548e4df8a3/f0872073-be83-48ab-8b6f-d2b59497ec4e)

**Comment by danielmutis** [comment]
Discussed this with @jkfran . I think we should open the first charm's config details by default. The content should have a title with that charm's name, and we agreed that it's best to remove the anchor links from the side navigation in this case. We will display a notification when the charm doesn't have any config details.

In a more general note, I think there isn't a real use case for this page. I would suggest we investigate a bit more what would actually be useful to users of bundles. In my opinion, if we want to show all the charms in a bundle we could do something similar to the [integrations page](https://zpl.io/bAryxKq) and link back to each charm's detail page.
