### ISSUE TITLE
Library layout template: rephrase "Publisher suggests"

### ISSUE THREAD

**Issue by sed-i** [canonical-web-and-design/charmhub.io#1165]
#447 and #509 Introduced the "publisher suggests" phrasing ~1yr ago and we might have a different understanding/perception of this now, which could potentially benefit some rephrasing.

https://github.com/canonical-web-and-design/charmhub.io/blob/e02b304805abaa6fbc15eea5513d4fdc6b6a674e/templates/details/libraries/libraries_layout.html#L29-L36

Specifically:
- Since a charm lib must be owned by a charm, there is only one charm that is the source of truth for a given library, so "publisher suggests" may seem a bit of a weak statement. Maybe "official libraries" or "original libraries" or "associated libraries" is a better phrasing, or maybe this title should be dropped entirely?
- It is common to use charm libs for relation management but the tooltip doesn't mention it explicitly.

RFC: @johnsca @mmanciop

**Comment by jkfran** [comment]
I moved this one for the next iteration since @Hollzz is on holiday.
