### ISSUE TITLE
Unreadable methods signature in charms library with typehints

### ISSUE THREAD

**Issue by heitorPB** [canonical-web-and-design/charmhub.io#1167]
Hello,

I was checking out the library for the Loki charm in https://charmhub.io/loki-k8s/libraries/loki_push_api and saw this:
![loki-lib](https://user-images.githubusercontent.com/13461702/138900388-421f50da-312f-4cae-8fdf-4f6d47b790aa.png)

The source code is available at https://github.com/canonical/loki-operator/blob/main/lib/charms/loki_k8s/v0/loki_push_api.py#L349 and looks like:

```python
def _validate_relation_by_interface_and_direction(
    charm: CharmBase,
    relation_name: str,
    expected_relation_interface: str,
    expected_relation_role: RelationRole,
):
```

Maybe this happens because of the newlines and the type hints?

What I'd like to see in CharmHub was the signature to be correctly rendered with the type hints.

**Comment by Lukewh** [comment]
Formatting has been improved with https://github.com/canonical-web-and-design/charmhub.io/pull/1294. We'll look into adding type hints now :)

**Comment by Lukewh** [comment]
@heitorPB digging deeper into the type hints - we recommend that you follow the "How to document your charm library" [0] to ensure types are properly displayed. The primary reason we recommend types be included in docstrings is to maintain a single source of truth, and secondly to ensure what is displayed to users is precisely what the library author intends.

We use the built-in python ast module to parse the source code and there is the potential to display malformed or incorrect types when converting back to a string.

I hope this helps :)!

[0] https://juju.is/docs/sdk/document-your-charm-library
