### ISSUE TITLE
How do I make my charm use the Filters from Charmhub.io?

### ISSUE THREAD

**Issue by heitorPB** [canonical-web-and-design/charmhub.io#1171]
Hello,

When I go to Charmhub.io I can see some filters (`AI/ML`, `Big Data`, `Cloud`, etc) on the left menu.

How do I make my charm "join" those categories? Is it something I specify in my `metadata.yaml`?

**Comment by jkfran** [comment]
Hi @heitorPB ,

You can include your desired category in the metadata.yaml of your charm:

```
categories:
    - cloud
```
 
This is the list of supported values at the moment:
```
ai-ml
big-data
cloud
containers
databases
logging-tracing
monitoring
networking
security
storage
```
Let me know if this helps you.

**Comment by heitorPB** [comment]
Thanks, @jkfran. will try adding that to our charms!

Are these categories/filters planned to be deprecated and removed?

**Comment by jkfran** [comment]
> Are these categories/filters planned to be deprecated and removed?

No, I don't think we will change it for a long period of time at least.

**Comment by heitorPB** [comment]
> > Are these categories/filters planned to be deprecated and removed?
> 
> No, I don't think we will change it for a long period of time at least.

Thanks! It appears to be some sort of miscommunication then, the [discourse post about metadata](https://discourse.charmhub.io/t/charm-metadata-reference/5213/5) removed the `categories` entry.

Also, can I suggest a new CharmHub category? We would love to also have a `High Performance Computing` (`hpc`) category there =D

**Comment by jkfran** [comment]
Hi @heitorPB 

I am sorry, I am afraid my previous answers were not valid. We are going to discuss it internally.

I will update you soon.

**Comment by jnsgruk** [comment]
Post on Discourse outlining the decisions made today: https://discourse.charmhub.io/t/charm-visibility-on-charmhub-tags-categories/5380

We can probably close this issue now? :)

**Comment by jkfran** [comment]
I think we can close it now. Thank you @jnsgruk

**Comment by heitorPB** [comment]
Thanks for clarifying this issue.

Where is the best place to suggest a new category in charmhub?

**Comment by jnsgruk** [comment]
> Thanks for clarifying this issue.
> 
> 
> 
> Where is the best place to suggest a new category in charmhub?

No worries. On Discourse :)
