### ISSUE TITLE
Unable to signin to Charmhub (502 error)

### ISSUE THREAD

**Issue by gruyaume** [canonical-web-and-design/charmhub.io#1175]
I am unable to signin to Charmhub.

When I click signin -> Ubuntu SSO, I'm redirected to a page that displays the following message: 502: This page isn’t working.

**Comment by cristinadresch** [comment]
@gruyaume we have tried to replicate the issue but with no luck. Could you try again please and send us a screenshot? Thank you

**Comment by gruyaume** [comment]
![Screenshot from 2021-11-25 14-47-46](https://user-images.githubusercontent.com/18486508/143494481-526f99f6-84ce-4f74-acef-d6bd8bc76536.png)

**Comment by gruyaume** [comment]
There you go, sorry for the delay. When I click sign in, I'm redirected to the ubuntu SSO, and then redirected to this 502 page. I'm not sure if I need to sign up before but if yes it's not clear where I can do so. Thank you,

**Comment by jkfran** [comment]
Hi @gruyaume ,

By taking a look into our logs the reason for the error is because the CSRF token has expired. This could happen when you take more than 1 hour to complete the login process (Since you click on "Sign in" until you come back to charmhub.io).

If you are sure this is not the cause of the issue please let us know and alternatively could you try to clean up your browser cookies and see if the error is still present?

Thank you.

**Comment by gruyaume** [comment]
I just re-tried on a different browser that had never attempted to log in and I had the exact same error. And I'm certain I didn't take 1 hour. Thank you,

**Comment by jkfran** [comment]
> I just re-tried on a different browser that had never attempted to log in and I had the exact same error. And I'm certain I didn't take 1 hour. Thank you,

I don't see any recent error on `https://charmhub.io/login/callback` or under `charmhub.io` is this still the URL where you get the error? Could you confirm the login process is working fine in other Canonical services like:

- https://ubuntu.com/
- https://snapcraft.io/ or https://snapcraft.io/login-beta

**Comment by gruyaume** [comment]
Yes I can correctly log in to ubuntu.com and snapcraft.io, but not on charmhub.

Here's the page where the 502 error is shown: https://charmhub.io/login/callback?code=-tomt5UewrDFU8jb4u4Etueb6i2NIIUD6KYpL8cEqn8&state=ImRiYjM5YWIzOWQwZjdmMDc2ZjFmZTgzYTUyMDQyNDMxNjdiNjJlZTki.YaTOdw.Pfq3vr-TJcjgYqrKvCYurKRoWVc

I also just asked my colleagues to test signing in and they both had the same error (Bartlomiej Gmerek and Javier Sanchez Fernandez) so I know I'm not alone here.

![Screenshot from 2021-11-29 07-58-56](https://user-images.githubusercontent.com/18486508/143872795-79ffe9f7-e084-43ad-9b77-a22d17982fb9.png)

**Comment by gruyaume** [comment]
It is worth to note that none of us ever logged in to charmhub. We're new users and are trying to have our charms published. I didn't see any `sign up` option, just this `sign in` one so maybe our accounts don't have the necessary permissions. Still this 502 page isn't what we would expect if it was a permission issue.

**Comment by jkfran** [comment]
Hi @gruyaume, I spoke with @matiasb about it and they are currently working on an issue with Candid for users that didn't authenticate before on Charmhub. So, it is probably the reason for this issue and why we can't reproduce it.

I'll keep you updated.

**Comment by jkfran** [comment]
Hi @gruyaume, could you check again? I was told today that Candid fixed the issue they were having.

**Comment by jkfran** [comment]
I confirmed with @gruyaume on Mattermost that this issue is solved 👍🏽
