### ISSUE TITLE
Charmhub.io - Library name should be the file's name

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/charmhub.io#1187]
The [design](https://app.zeplin.io/project/5f92a9530029eeac84ae9589/screen/601928c0780bfe0acf316da6) for this is ready and signed off but wasn't implemented.

The name (h2) of a library should be the file's name as intended in the design. Example below:

how it currently looks like:
<img width="1190" alt="Screenshot 2021-11-30 at 13 29 43" src="https://user-images.githubusercontent.com/36884067/144056675-2860e171-824a-45a8-a39f-0a5066519c24.png">

how it should look like:
<img width="1204" alt="Screenshot 2021-11-30 at 13 30 17" src="https://user-images.githubusercontent.com/36884067/144056729-3259f1b3-019f-4b37-a690-85e7054c053c.png">

**Comment by jkfran** [comment]
Hey @steverydz, this name is not comming from the API. I think we are generating it. You can copy what we have here:
![image](https://user-images.githubusercontent.com/6353928/144827535-0839225b-ea32-49eb-a65d-7a877fd87a7e.png)
