### ISSUE TITLE
charmhub.io - Footer link not working

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/charmhub.io#1190]
Go to the footer and click <What is Charmhub?> - doesn't link anywhere.

https://user-images.githubusercontent.com/36884067/144228823-22657ee6-e297-4901-8c90-4460a76ff70d.mov

**Comment by steverydz** [comment]
Where should this link to? The about page?

**Comment by anasereijo** [comment]
[copydoc](https://docs.google.com/document/d/1mps4SOa8_DA25fccYor3wxwV3ulQiD-uaocDHmaGmhw/edit)

**Comment by anasereijo** [comment]
asked David Booth
