### ISSUE TITLE
https://charmhub.io/jaas yields 404 after migration

### ISSUE THREAD

**Issue by Gleland** [canonical-web-and-design/charmhub.io#1228]
Hello, we have some internal documentation that links to JAAS (https://jujucharms.com/jaas), and it looks like after the redirect changes, this now points users to https://charmhub.io/jaas, which shows a 404. Perhaps this should redirect to https://jaas.ai/jaas instead, or update the page to give the appropriate information? Thanks!

**Comment by jkfran** [comment]
@anthonydillon what do you think about this?

**Comment by anthonydillon** [comment]
Looks like there was a mistake in the logic. Will address today.

**Comment by anthonydillon** [comment]
Sorry missed read this. There have been no changes to the redirects on jujucharms. Is this a new redirect?

**Comment by jkfran** [comment]
@anthonydillon what's your opinion about changing the redirection to jaas.ai/jaas ? Is that the right place? I can change the redirection.

**Comment by anthonydillon** [comment]
Yes it should do. I have filed an RT to add this redirect rule to jujucharms.com.

**Comment by jkfran** [comment]
Closing this issue, thank you for reporting it.
