### ISSUE TITLE
subordinate charm reporting incorrect series

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#1247]
We have a charm, https://charmhub.io/ubuntu-advantage which has the following in its `metadata.yaml`:
```
series:
  - focal
  - bionic
  - xenial
```
Currently it only reports availability on 20.04, however.

**Comment by jkfran** [comment]
We are showing this property from the `default-release.revision.bases` field on the API, this is the call:
`https://api.charmhub.io/v2/charms/info/ubuntu-advantage?fields=default-release.revision.bases`

In this case, we are getting just Ubuntu 20.04.

**Comment by jkfran** [comment]
We had many issues before (https://github.com/canonical-web-and-design/charmhub.io/issues/1073, https://github.com/canonical-web-and-design/charmhub.io/issues/1255) requesting us to show the right platform from the revision bases (`default-release.revision.bases`).

So I am not sure about the `series` in the metadata.yaml. Let me ask @Roadmaster

**Comment by jkfran** [comment]
Looks like this property is deprecated anyway.

> List of supported charm base platforms/versions. In the form of “focal”, “bionic”, “centos7” etc. Deprecation: to be supplemented by containers/bases.

https://discourse.charmhub.io/t/charm-metadata-v2/3674

I am closing the issue unless it is completely necessary, feel free to reopen it.
