### ISSUE TITLE
subordinate charm not obviously listed as such

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#1248]
I noticed that a subordinate charm such as https://charmhub.io/ubuntu-advantage doesn't have any indication that it's a subordinate. Is this intended? It feels like something that would be worth calling out explicitly, but let me know if we should simply make that more prominent in the documentation.

**Comment by jkfran** [comment]
Issue reported to the store team to expose this property:
https://bugs.launchpad.net/snapstore-server/+bug/1960423

**Comment by mthaddon** [comment]
Btw, this seems to be a duplicate of https://github.com/canonical-web-and-design/charmhub.io/issues/1015.

**Comment by jkfran** [comment]
Thank you, we didn't notice it. I am going to close this issue as we have the other one.
