### ISSUE TITLE
Subnav blocking page content

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/charmhub.io#1251]
There is a subnav that is displayed on the page which is blocking the page content with no obvious way to hide it. Confirmed on Chrome and FF.

![containerd-charmhub](https://user-images.githubusercontent.com/24707086/153486275-db087a98-2e9c-479e-b04a-dc5ea877b114.png)

https://charmhub.io/containers-containerd/docs

**Comment by cristinadresch** [comment]
@cjohnston1158 this is fixed now, thanks for reporting it
