### ISSUE TITLE
UX relation tab: Write and publish discourse post

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/charmhub.io#1262]
Write and publish a discourse post with the wireframes asking for feedback from the community.
- publish post on [charmhub requets category](https://discourse.charmhub.io/c/charmhub-requests/46) and post a link to it on this [post about relations](https://discourse.charmhub.io/t/where-are-relations/5652)

**Comment by anasereijo** [comment]
@jkfran  @clagom could you please have a look and leave comments/suggestions? 

[draft here](https://docs.google.com/document/d/1MJKXiqBZZIVS20kZ_fAU7X7OMoRUOmvF02ZCzLp7n4w/edit?usp=sharing)

in case you need to see the wireframes bigger [here is the link ](https://www.figma.com/file/EtqAgsBQJmOf9g4fbW3dP1/Charmhub---Integration-tab?node-id=0%3A1)

**Comment by anasereijo** [comment]
@clagom  @jkfran any thoughts? :D

**Comment by jkfran** [comment]
It looks fantastic to me. The design looks like a final version to me, but I am a bit worried about what the store team will deliver this cycle.

**Comment by clagom** [comment]
Looks great, thanks @anasereijo. I added just a minor comment. You also mention that this is part of a longer vision so that should set the expectations for V1 but still providing feedback on the final UX.
