### ISSUE TITLE
prep meeting/presentation about Relations 

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/charmhub.io#1263]

**Comment by anasereijo** [comment]
@clagom I prepped some slides for next week's presentation. Could you please let me know your thoughts?

[link](https://docs.google.com/presentation/d/1ha_vAoqDHTI3qln2DH1_MfRjfPoCXVyud6SdvVgx_fg/edit?usp=sharing)

**Comment by clagom** [comment]
I think it's good overall, I left some comments @anasereijo maybe we can have a quick chat before the meeting
