### ISSUE TITLE
Remove the Juju version warning and find a better solution

### ISSUE THREAD

**Issue by jkfran** [canonical-web-and-design/charmhub.io#1272]
Reported by @jnsgruk:

![image](https://user-images.githubusercontent.com/6353928/157666262-07cbe043-a6ee-4990-adfa-76a828c44961.png)

**Comment by anasereijo** [comment]
@AnnSoMuller as discussed see the juju 2.9 warning on the tooltip.

@spencerbygraves not sure if there's anything we can do visually to make this work better? Any thoughts?

![Screenshot 2022-04-20 at 10.55.43.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/d5b9f196-c6f4-4996-b2b1-1419cc0cbbde)

**Comment by AnnSoMuller** [comment]
great! +1

**Comment by jnsgruk** [comment]
This looks much more friendly!

Note that it may be worth taking into consideration the `assumes` functionality in later Juju releases that might provide more fine-grained requirements on a per-charm basis: https://juju.is/docs/sdk/assumes

**Comment by jkfran** [comment]
> This looks much more friendly!
> 
> Note that it may be worth taking into consideration the `assumes` functionality in later Juju releases that might provide more fine-grained requirements on a per-charm basis: https://juju.is/docs/sdk/assumes

Hi Jon, thank you for having a look. I created an issue about supporting `assumes` so we could work on it as a new feature: https://github.com/canonical-web-and-design/charmhub.io/issues/1330

**Comment by spencerbygraves** [comment]
Looks fine to me. Thanks.
