### ISSUE TITLE
Design for Charm embedable cards for a charm that doesn't exist

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/charmhub.io#1275]
Currently, if someone attempts to embed a charm (or bundle) that doesn't exist, we show the default 404 page that doesn't fit or give the user any information that they attempted to view a charm (or bundle).

**Charm card for charmhub.io:**
First card works, second and third are broken.
![image](https://user-images.githubusercontent.com/479384/157688645-0897ebc2-041e-40fb-9c89-888373b60deb.png)

**Embeddable card for publishers to embed:**
Working:
![image.png](https://images.zenhubusercontent.com/59316f3551aa2c3057803f4b/6cc0a602-c8b6-4e10-8997-7b4732fa3656)
Broken:
![image.png](https://images.zenhubusercontent.com/59316f3551aa2c3057803f4b/a3045870-acaf-4b41-815c-5e0601c3ef44)

**Comment by cristinadresch** [comment]
Charm not found card design needed

**Comment by cristinadresch** [comment]
@spencerbygraves you think you would be able to look at this next iteration? we need a 404 page design that fits within a card size

**Comment by Lukewh** [comment]
@spencerbygraves has promised me he'll do it on Thursday. He said if he doesn't he knows he'll be disappointing both himself and the rest of the team.
No pressure.

**Comment by spencerbygraves** [comment]
:sob:

**Comment by spencerbygraves** [comment]
I've spoken to @Lukewh about using this [Vanilla pattern](https://vanillaframework.io/docs/examples/patterns/empty-state/no-content) with this [icon](https://assets.ubuntu.com/v1/4de1c56c-404_v1.svg).
