### ISSUE TITLE
Overview should include anchors for Markdown reference links to headers

### ISSUE THREAD

**Issue by afreiberger** [canonical-web-and-design/charmhub.io#1296]
When viewing the documentation for charm nova-compute, there is reference in the documentation to the Availability Zones section of the document.  this uses Markdown Links to render links to section headers.

https://raw.githubusercontent.com/openstack/charm-nova-compute/master/README.md

We should ensure that each Markdown header gets an anchor tag that can be used for deep dive through large charm documents.

I'm unable to find the section automatically with the reference link:
https://charmhub.io/nova-compute#availability-zones

**Comment by Lukewh** [comment]
Thanks for the suggestion @afreiberger, I've added it to our next iteration (starts next week) :)

**Comment by evilnick** [comment]
I believe this is a limitation of the version of discourse we are using, which doesn't generate ids automatically for each heading. Currently docs authors have to manually create the id tags to make anchors for docs

**Comment by Lukewh** [comment]
We can add them on the Charmhub details page by generating the ID at render. It would make them change if headings etc. change, but should be ok for the majority of cases?

**Comment by pmatulis** [comment]
In this particular case of a charm's landing page in the Charmhub, the Markdown source does not reside in Discourse but in the charm's repository.
