### ISSUE TITLE
Search for magpie charm does not show results

### ISSUE THREAD

**Issue by szeestraten-ntnu** [canonical-web-and-design/charmhub.io#1304]
I am searching for charms with the name `magpie` on https://charmhub.io/ which returns no results.

![image](https://user-images.githubusercontent.com/25442190/160125408-af32eeb4-0d06-42d5-b26e-dcdab287132d.png)

However there are at least 3 charms with `magpie` in the name according to Google search:

![image](https://user-images.githubusercontent.com/25442190/160125343-84c9e061-4f9e-4363-a5d4-c69c0f7b6fb6.png)

* https://charmhub.io/admcleod-magpie
* https://charmhub.io/majduk-magpie
* https://charmhub.io/openstack-charmers-next-magpie

**Comment by Lukewh** [comment]
Thanks for the report. It looks like those charms are marked as unlisted by the publishers, which means they won't show on the Charmhub search (but you can visit the URL directly). The bug here is that we're not telling search engines to **not** index these pages on charmhub.io. We'll work on a fix, thanks :)!

**Comment by szeestraten-ntnu** [comment]
Hi @Lukewh, thanks for your quick reply. Just to double check, are they unlisted by active choice of the owner or because of a default setting when they got migrated from the old Charmstore? I would assume that the charm in the old `openstack-charmers-next` namespace was not private/hidden.

**Comment by Lukewh** [comment]
@szeestraten-ntnu, I'm not 100% certain, but I believe the migration made select charms unlisted so I'm not sure for individual charms, that would be a question for the charm maintainer.
An update on the issue described in this PR - the store team will have the API updated with the relevant fields for the front end in the next week.

**Comment by szeestraten-ntnu** [comment]
@Lukewh OK, thanks for the update. Looking at the [Charmhub Transition FAQ](https://discourse.charmhub.io/t/charmhub-transition-faq/5636) I see that _all_ non-promulgated charms that were migrated are hidden by default from search by a flag which is a shame as I am sure there are many charms which will be hidden and charm authors who have not picked up on this. 

> This is usually related to “findability”. Charmhub has a “show charm in search results” flag, which, for imported charms, is only set for promulgated charms.

> This means that if your charm was not promulgated, it will not show up in search results. 

> The above policies were put in place to showcase promulgated charms and avoid potentially low-quality, experimental namespaced charms polluting search results.

> To change visibility status, please ask the Store team (or in the [Charmhub forum](https://discourse.charmhub.io/)) to make them listed, once you’re ready to have them show up in search results. Note that any change in visibility status should be authorized by the Charmhub product managers.
