### ISSUE TITLE
Add the list of charms that are in the bundle [bundle detail page] 

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/charmhub.io#1312]
###  [bundle detail page]
It would be very useful to have the list of the charms that a bundle contains displlayed in the "overview" landing page of the bundle:

![Screenshot 2022-04-01 at 09.28.36.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/379b8bec-c2ae-4918-a647-5e3a422f65b5)

Above "relevant links"
Similar to the list we display in "configure" tab, but could be a static list or just likes to the relevant charms' detail pages.

The end goal is to have the topology of the bundle represented here instead, but it's going to take longer and we didn't plan this part of the functionality for the annotations yet.

**Comment by lyubomir-popov** [comment]
Assigning to myself to do part of the work here after speaking to @AnnSoMuller.
I'll focus on creating a clear visual distinction between single charms and bundles.

**Comment by lyubomir-popov** [comment]
My proposal:

![image.png](https://images.zenhubusercontent.com/59d2496bb0222d5de479ea17/a75d7fcb-cb93-423c-9492-5836474b2c27)

**Comment by clagom** [comment]
Hey @lyubomir-popov thanks for the proposal. It is something we can explore for sure, but the original ticket was about detail page only. I think there it's a 0-effort win that we can apply directly.
The other one is a proposal that we need to explore and discuss with Holly and others. Can you please maybe revert the original issue and open a new one for the rest? Thanks! CC @Lukewh @AnnSoMuller

**Comment by lyubomir-popov** [comment]
Ah sure sorry @clagom I was pointed to this issue and thought I should submit the proposal here. I've moved it to https://github.com/canonical-web-and-design/charmhub.io/issues/1315

**Comment by clagom** [comment]
Thanks @lyubomir-popov

**Comment by AnnSoMuller** [comment]
relates to #2395 and #1315

**Comment by AnnSoMuller** [comment]
[here](https://app.zeplin.io/project/623c85b9b27d9fa62165f655/dashboard) is the zeplin file with 2 different options
Knowing that the IA will change soonish with the [documentation discussion](https://docs.google.com/presentation/d/1VIGHoeGW9FwWFLrt4RLa1dbQf3T7caomO-VhDrju578/edit#slide=id.g1245bd5b149_0_67) happening (slide 9 and 10) to have "Docs" and "Overview" merged into a "Home" Tab

**Comment by Lukewh** [comment]
A is my preferred. But the new "home" will throw a spanner in the works. I think we should move forward either way, unsure how long it'll take to get the home changes agreed, designed and done. We also need to take into account the list of charms for alignment.

**Comment by anasereijo** [comment]
I also like version A the most. 👍 
Do we know how many charms a bundle has on average? Will it be a case where we have to display too many? Just wondering if that's the case how well it would fit the layout.

Also, I see we changed how we visually display bundles at the top of the page. I see now we have a tag BUNDLE. Wondering if that's enough to show it's a bundle compared to what we currently have?

<img width="277" alt="Screenshot 2022-04-28 at 09 21 05" src="https://user-images.githubusercontent.com/36884067/165711473-410b61ce-8c4e-4e74-9499-832bf7890779.png">

**Comment by steverydz** [comment]
I concur with @Lukewh and @anasereijo

**Comment by AnnSoMuller** [comment]
@anasereijo Thanks!
Here is almost the "worst" case, with 33 Charms (another one has 34, that is the maximum number of Charms within a Bundle). The average is around 5-10.

Visually, we would stay coherent with the visual distinction we have on card. 
Indeed, next to the title, we won't have the same icon anymore however this list of icons/logo for the Charms will emphasis the difference :)

![Screenshot 2022-04-28 at 10.51.02.png](https://images.zenhubusercontent.com/606c1e6c5aab87d8cd196107/a7e9940c-1b9e-42e2-ac18-48f4762d3337) ![Screenshot 2022-04-28 at 10.51.27.png](https://images.zenhubusercontent.com/606c1e6c5aab87d8cd196107/b190cef5-7507-43cb-a384-143913414806)

**Comment by anasereijo** [comment]
@AnnSoMuller thanks! looks great 👍
