### ISSUE TITLE
Library introduction on individual charms is too long/misleading

### ISSUE THREAD

**Issue by jnsgruk** [canonical-web-and-design/charmhub.io#1313]
Hi folks

Have had a couple of discussions with @evildmp and Holly, I think the "Introduction" page we display on Libraries tab per charm is far too long, and even misleading in places. I have attached a screenshot, where the intro gives examples about MySQL, despite the charm being [Prometheus](https://charmhub.io/prometheus-k8s/libraries).

My suggestion is that we either remove this "Intro" section completely, or make it much shorter and just link to the documentation pages about libraries: https://juju.is/docs/sdk/libraries

![image](https://user-images.githubusercontent.com/668505/161234362-0aa246a1-0099-476a-83d3-c3b028310d45.png)

**Comment by Lukewh** [comment]
I'll take a look to see how this intro is being added and move forward accordingly. If we're injecting it (which I imagine we are), we should look to improve the UX - people don't want to read an intro, they want to see the libraries - if libraries exist.

**Comment by anasereijo** [comment]
@jnsgruk could you please let us know your thoughts? thank you

**Comment by AnnSoMuller** [comment]
works for me :)
