### ISSUE TITLE
Update charm hub cards so bundles are visually distinct from individual charms

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/charmhub.io#1315]
###  [Home page]
It would be nice to have the list of Charms displayed in the cards of Bundles
![Screenshot 2022-04-01 at 12.04.20.png](https://images.zenhubusercontent.com/606c1e6c5aab87d8cd196107/9d8d70e9-4a33-486b-952b-b776a461e9c9)
It could emphasis the visual distinction between Charms and Bundles
It could be the icon with the +XX that expand, a tooltip or within the Card itself etc.
To be explored Visually :)

-

During the last Design Assembly we discussed that bundles are not different enough from individual charms. My proposal to make them more distinct:

Two of the elements repeat, the rest don't. This aligns the ones that do repeat, and makes optimal use of the remaining space to display the rest of the item:

![image.png](https://images.zenhubusercontent.com/59d2496bb0222d5de479ea17/a75d7fcb-cb93-423c-9492-5836474b2c27)

**Comment by AnnSoMuller** [comment]
relates to #2395

**Comment by AnnSoMuller** [comment]
thanks @lyubomir-popov for that proposal, I already implemented the visual suggestions for #2395

**Comment by AnnSoMuller** [comment]
I have suggested changes in the Fima file and agree and the decision made :)
So +1 for me :)

**Comment by spencerbygraves** [comment]
@lyubomir-popov @AnnSoMuller I have a couple of thoughts.

What does this look like on the details page?

Also, not every charm has an icon, how do we avoid a list that shows a number of grey/blank icons? From memory the current design picks the first two specified by the author, if that's still the case would we have any way of putting the blank ones at the end? It might be worth testing a few in case.

Thanks.

**Comment by AnnSoMuller** [comment]
@spencerbygraves thanks for these thoughts! :)
Indeed, we have #1312 to think about how to display this list in the detail page: that will require a bit of UX with "final" visual touch.
As far as I am concerned, it is ok to start with the visual distinction that @lyubomir-popov suggested and provide more details like interactive tooltips or labels etc. if there is the required need of a proper list.
However, while implementing it we should have a look at the order to display them, sure!
Thanks!

**Comment by lyubomir-popov** [comment]
If an icon is mising, why not a circle with an initial inside it?
Another option would be just a truncated list of names instead of a grid of circles, wth a see more link or something. The dots are nice, but they convey little information.

**Comment by lyubomir-popov** [comment]
sorry @cristinadresch I think there's a little more to discuss here

**Comment by AnnSoMuller** [comment]
@lyubomir-popov keep in mind that the usec ase here is a visual distinction between Charms and Bundles
We don't focus on solving an assumption of a proper list requirement :)
Indeed, a letter in a circle can improve the point raised by @spencerbygraves

**Comment by spencerbygraves** [comment]
Perhaps an adjustment to the existing design would be enough.

![image](https://user-images.githubusercontent.com/9105999/162423722-9e0785ba-af2a-4f7b-a1b2-8d250e7bad82.png)

**Comment by lyubomir-popov** [comment]
@spencerbygraves The problem we were trying to solve was making bundles visually distinct enough. As I understood it, the version above was deemed not clear for some reason.

**Comment by AnnSoMuller** [comment]
@spencerbygraves Indeed your suggestion improve the current design :)
However @lyubomir-popov proposal goes a bit deeper, taking into account the discussion we had to provide more information in the Charm detail page, see the next improvement #1312
So that we are going to have a common theme :)
A letter in the bubbles with no icon can be enough a (simple) start and we still have room to iterate if needed.
Does that sound as a plan @lyubomir-popov and @spencerbygraves ?

**Comment by anasereijo** [comment]
@spencerbygraves @lyubomir-popov have you come to an agreement regarding this?

**Comment by spencerbygraves** [comment]
@anasereijo it sounds like @AnnSoMuller is happy with @lyubomir-popov's solution, with the addition of a letter for charms without an icon. Thanks.
