### ISSUE TITLE
Bug: charmhub.io/topics

### ISSUE THREAD

**Issue by Hollzz** [canonical-web-and-design/charmhub.io#1320]
Howdy!

Found a bug on https://charmhub.io/topics - when the window is narrow and the "> Filters" box can be seen, when you click the "> Filters" box, the list of filters appears and immediately disappears, leaving a black screen with the text from the page behind. Please let me know if you need more details!

Best,
Holly

**Comment by anthonydillon** [comment]
I still see this issue on staging.
