### ISSUE TITLE
Wrong command in livepatch configuration example

### ISSUE THREAD

**Issue by camille-rodriguez** [canonical-web-and-design/charmhub.io#1326]
On this page https://charmhub.io/livepatch-charmers-canonical-livepatch-on-prem-bundle , this command `$ juju configure livepatch url_template='http://{haproxy}/patches/{filename}' ` is wrong. It should be 
`$ juju configure livepatch url_template='http://{haproxy}/v1/patches/{filename}'`

Confirmed by this page and tests https://ubuntu.com/security/livepatch/docs/on_prem/deployment

**Comment by tasdomas** [comment]
This is a bundle readme issue

**Comment by Lukewh** [comment]
> This is a bundle readme issue

Indeed - though, it's difficult to know how to contact "Livepatch charm developers" without any contact details on the page.

**Comment by tasdomas** [comment]
> 
> Indeed - though, it's difficult to know how to contact "Livepatch charm developers" without any contact details on the page.

And that is a charmhub issue :)

**Comment by Lukewh** [comment]
The field is there for Livepatch charm developers to add their contact details ;)

https://charmhub.io/livepatch-charmers-canonical-livepatch-on-prem-bundle/listing
![image](https://user-images.githubusercontent.com/479384/162976784-8edd6758-5bad-426a-9912-4b1294d4875d.png)

**Comment by camille-rodriguez** [comment]
Two things I'd like to add here. First, how do we expect to improve our public docs if we're playing ping pong at "who's responsible" ? This issue was closed without anything being fixed. Sure, it might be the charm team's responsibility, but from the website, the only was to report an issue with the documentation is to "report a bug" here. This is a really bad experience for the user/customer. I'd expect this bug to be forwarded to the relevant team instead of simply being closed. 

Second thing, your link leads to a 404 @Lukewh 
![image](https://user-images.githubusercontent.com/42066843/169593606-622fb830-d03f-4190-912d-9a589f95449e.png)

**Comment by Lukewh** [comment]
Hi @camille-rodriguez, thanks for the feedback.

Unfortunately if a charmer doesn't provide information for users to contact them it's difficult for us to know who to forward the request to. In this case we did know, so could have done a better job so I apologize. Long term, however, it's not possible for us to triage issues for every charm or bundle on Charmhub.

A potential solution moving forward, especially for internal charm teams, is to educate charmers on how important it is to provide more complete metadata. We'll be sure to look into how best to approach this from our side, but anyone within Canonical should contact individual teams to suggest improvements.

I believe the link you're referring to is "Report a bug on this site" in the footer of every page - we will review the wording here to make the intention clearer.

Apologies for the link I posted, only logged in collaborators of the bundle will see that page as it's one of the charm admin pages, I should have clarified that when I commented.

If you contact the Livepatch team in ~Livepatch on mattermost they should be able to help with the original issue 🙂

**Comment by camille-rodriguez** [comment]
Hi, thanks for the quick reply here. I understand that responsibilities lie in different teams, and it might be difficult to bridge gaps sometimes. I had reached out to them on mattermost btw and shared this link. Actually, I realize now that @tasdomas was that person and he already commented here. @tasdomas, did you file a separate bug on the charm docs and I'm simply now aware of it ?

I agree that revisiting the wording for reporting issues on this site would help. It used to be really simple to know where a charm code was hosted and how to report bugs to them, and this seems to have disappeared from the new store.
