### ISSUE TITLE
Trying to register a reserved charm name gives confusing error message

### ISSUE THREAD

**Issue by Roadmaster** [canonical-web-and-design/charmhub.io#1344]
Trying to register a reserved charm name in https://charmhub.io/register-name, I get this error message:

The name 'weebl' is not valid. It should only have ASCII lowercase letters, numbers, and hyphens, and must have at least one letter. 

This is misleading, it should tell me the name is reserved.

The API should be sending the correct code, but in the charmhub.io Python thingy it gets lumped together with "api-error" (unless the response is actually an api error?)

```
    except StoreApiResponseErrorList as api_response_error_list:
        for error in api_response_error_list.errors:
            if error["code"] in ["api-error", "reserved-name"]:
                return redirect(
                    url_for(
                        ".register_name",
                        entity_name=data["name"],
                        invalid_name=True,
                    )
                )
```

So:
- Can you check whether the API is returning api-error here? If so, please let me know so we can look into it.
- If the API is returning reserved-name, please change the error message so it indicates it is a reserved name.

Thanks!

**Comment by Roadmaster** [comment]
I've registered `weebl` manually for the requester, but you can use `zygrib` to test.

**Comment by jkfran** [comment]
Thank you for reporting it @Roadmaster
