### ISSUE TITLE
Duplicate Platforms in the web page

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/charmhub.io#1346]
For example, this page has two entries for the same `Ubuntu 20.04 18.04 16.04` twice.

https://charmhub.io/etcd?channel=stable

![image](https://user-images.githubusercontent.com/4356209/169808058-ee7c60cd-8f64-412c-a665-9644822a2063.png)

In the different channel, it actually has three entries with the same content.

https://charmhub.io/etcd?channel=edge

![image](https://user-images.githubusercontent.com/4356209/169808121-d8d97495-bf83-41f5-9b1c-4e25b66184e5.png)

**Comment by steverydz** [comment]
@nobuto-m Thanks for reporting this issue. We will look into this.

**Comment by steverydz** [comment]
Thanks for reporting this @nobuto-m. It's now fixed and live in production.
