### ISSUE TITLE
Releases: Identify improvements from snapcraft.io user testing

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/charmhub.io#146]
Identify the most critical problems and address them here. Also synchronize with snapcraft.io.

**Comment by danielmutis** [comment]
We need to dig deeper into how some of the elements of the release UI translate for Charmhub and what the API provides. 
In terms of usability, I think the following steps would be a good path forward to improve the current build:

1. Implement designs for the modular table. This would fix:
    1. Colours (also align solutions with RBAC)
    2. Drag and drop discoverability
    3. Icons used within the cells 
    4. Make sorting clearer
    5. Expanding table functionality/interaction
2. Make sure the table also works without drag and drop
    1. Use of radio buttons instead of checkboxes
3. Replace revision number with something more meaningful
4. Understand the different alerts and how to include them in the design in a less disruptive way
5. Unify the “most recent” and launchpad tabs
6. Implement the same sticky bar for saving changes as on the listings tab.
7. Add links to build (not sure how this works in CH)

The source of this list is [this doc.](https://docs.google.com/document/d/10sI4ZlYpXG2QBg2KYV0xA5E6BUVFEACEGXzqL1YUySA/edit#)

@clagom @cristinadresch @tbille
