### ISSUE TITLE
"Bugs" link for postgresql charm doesn't match `metadata.yaml`'s `issues` entry

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#1591]
Hello,

Currently the homepage of https://charmhub.io/postgresql correctly points to https://github.com/canonical/postgresql-operator, however the "Submit a bug" link points to https://bugs.launchpad.net/postgresql-charm. This charm has recently been taken over by the Data Platform team, and the location of the project has changed from https://launchpad.net/postgresql-charm to https://github.com/canonical/postgresql-operator. Looking at the contents of metadata.yaml for the charm (https://github.com/canonical/postgresql-operator/blob/main/metadata.yaml) I see:
```
issues: https://github.com/canonical/postgresql-operator/issues
```
Any ideas why it's not using that URL but still listing the old bugs URL?

Thanks, Tom

**Comment by taurus-forever** [comment]
Hi @mthaddon,

I believe it is the same story as described for MySQL in https://discourse.charmhub.io/t/question-why-charm-mysql-ignores-issues-attribute-in-metadata-yaml/10029 (it is no longer topical there, as we have closed `latest/stable` already).

For PostgreSQL it supposed to be addressed after closing `latest/stable` too. Happy to address it faster if possible!
