### ISSUE TITLE
Charm pages should be able to link to external web pages, such as blog posts  

### ISSUE THREAD

**Issue by timClicks** [canonical-web-and-design/charmhub.io#165]
**Is your feature request related to a problem? Please describe.**

The charm web pages are quite static. It would be nice to be able to demonstrate that they have users.

**Describe the solution you'd like**

The `ceph-osd` charm has quite a large community. It includes external contributors who [write howto](https://zeestrataca.com/posts/expanding-ceph-clusters-with-juju/) guides, for example. It would be great if posts like these could be added to the charm/bundle's page.

**Describe alternatives you've considered**

Status quo.

**Additional context**

**Comment by Lukewh** [comment]
@timClicks the way this works with snapcraft.io is by tags on ubuntu blog posts. 
We've talked about adding a pingbacks, but it hasn't progressed. I'd suggest you talk to the snap advocacy team (wimpey, popey etc.). If this is something that could be useful across multiple products/ sites we should spec and add it to next cycle. I'm happy to work with you all on figuring it out :+1:

**Comment by danielmutis** [comment]
We allow users to have links in their readmes and also to add external links in their metadata (such as bug links, source code, etc). I am going to close this, unless you think it's still an issue.
