### ISSUE TITLE
Align navigation menu to juju.is

### ISSUE THREAD

**Issue by massigori** [canonical-web-and-design/charmhub.io#1659]
Please align the navigation menu to juju.is: replace 

- about -> Community
- Learn -> Docs
- Contribute -> Blog

The full structure can be found in the juju.is [copydoc](https://docs.google.com/document/d/1IFnKQ3GQth7HSo1VlDy4nRyoFYPL9fjJN8jNuY8Nr2Q/edit?usp=sharing)

![image](https://github.com/canonical/charmhub.io/assets/100278053/21ed2747-7a0a-4bca-81b9-f440afbd900e)

**Comment by AnnSoMuller** [comment]
pinging @tmihoc to make sure we all agree on moving away from the actual navigation structure :)
