### ISSUE TITLE
"submit your operator" takes you to the operator framework github page

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/charmhub.io#358]
![Screen Shot 2020-09-22 at 3 38 44 PM](https://user-images.githubusercontent.com/532033/93940465-bdcb0580-fce9-11ea-94f4-20bce1c1149f.png)

I expected this to take me to somewhere with documentation on how to submit an operator

**Comment by barrymcgee** [comment]
Reopening this issue as my PR was closed, not merged.

@tbille Note, @mthaddon raised this same issue just yesterday: https://github.com/canonical-web-and-design/charmhub.io/issues/413

**Comment by tbille** [comment]
We will be working on a new site for the framework. Keeping this issue open until the site is not live.

**Comment by tbille** [comment]
This section is not there anymore.
