### ISSUE TITLE
"kubernetes" search returns no results

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/charmhub.io#361]
![Screen Shot 2020-09-22 at 3 47 35 PM](https://user-images.githubusercontent.com/532033/93941139-0636f300-fceb-11ea-962a-89fcd852c018.png)

**Comment by clagom** [comment]
I think this might need a higher priority, let's discuss it in tomorrow's catchup.

**Comment by tbille** [comment]
@jkfran can you investigate if we can do full search on `platfrom` and `description`. If this is not case please open an issue on store side.

**Comment by jkfran** [comment]
I created an issue for the store team about this:
https://bugs.launchpad.net/snapstore-server/+bug/1906804

I don't know if we should keep this issue open here as is now on their side.

**Comment by jkfran** [comment]
🥳 

https://charmhub.io/?q=kubernetes

I think we can close the issue now. There are still pending work on the store side, you can track the progress in the Launchpad bug mentioned in my previous comment.
