### ISSUE TITLE
Add 500 & 404 pages

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/charmhub.io#37]

**Comment by danielmutis** [comment]
[404](https://zpl.io/2j0O0oW) and [500](https://zpl.io/am0J0zr) designs.

Please feel free to add comments on how to sass it up (voice of the product).

**Comment by solazio** [comment]
@danielmutis for now I have implemented the [design](https://staging.charmhub.io/sad/asdasd) we use on canonical.com if you want to take a look and get any inspiration.

**Comment by danielmutis** [comment]
I think this is fine @solazio but not great. It doesn't provide any possible explanations for why the error happened, and doesn't provide a clear CTA of where to go next.

**Comment by spencerbygraves** [comment]
@danielmutis could you use the [image](https://assets.ubuntu.com/v1/4de1c56c-404_v1.svg) from the Canonical page, with your content on the right?

**Comment by danielmutis** [comment]
@spencerbygraves thanks, I have updated the design with that image.

**Comment by Lukewh** [comment]
Is there a different issue to implement these changes? If not we should reopen this.

**Comment by solazio** [comment]
> Is there a different issue to implement these changes? If not we should reopen this.

yes https://github.com/canonical-web-and-design/charmhub.io/issues/50

**Comment by danielmutis** [comment]
@solazio  Then I will close this one.
