### ISSUE TITLE
Add platform filter to homepage

### ISSUE THREAD

**Issue by danielmutis** [canonical-web-and-design/charmhub.io#477]

**Comment by danielmutis** [comment]
[Option 1](https://zpl.io/2yN7Q4w)
[Option 2](https://zpl.io/aRZqjn0)

**Comment by clagom** [comment]
Thanks @danielmutis, personally I think Option 1 works better, and will also scale better when we have 'architecture', too.
We won't have to display 'series' within platforms at this level, so I think the drop-down won't get too complicated.

**Comment by pmahnke** [comment]
I agree, you will not change your platform more than once, so the dropdown
feels more like a permanent choice.

**Comment by spencerbygraves** [comment]
@danielmutis happy with version 1. Thanks.

**Comment by tbille** [comment]
done
