### ISSUE TITLE
Typography on actions tab

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/charmhub.io#479]
To get there:
- Create file: `.env.local` and add:
```
CHARMSTORE_API_URL=https://api.staging.snapcraft.io/
```
- `dotrun`
- http://0.0.0.0:8045/ubuntu-qa/actions
- This is the only charm that has an action. It only has one.

**Comment by tbille** [comment]
Updated design: https://zpl.io/Vx7y57R
Next step: integrate on the site
