### ISSUE TITLE
Improve the empty state of the actions tab

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/charmhub.io#480]

**Comment by tbille** [comment]
https://zpl.io/2GrGdz4

**Comment by clagom** [comment]
Design wise, would look like the empty doc page:
<img width="774" alt="Screenshot 2020-11-10 at 09 20 53" src="https://user-images.githubusercontent.com/1953388/98654296-0be9a600-2336-11eb-8633-6a35615d956d.png">
But with this copy:
https://docs.google.com/document/d/1WRsmSC2x-mh5fuT1S_SaWs0apbp-C8dzb_6x_TIvehg/edit
<img width="608" alt="Screenshot 2020-11-10 at 09 21 18" src="https://user-images.githubusercontent.com/1953388/98654339-1b68ef00-2336-11eb-9021-839863cea830.png">

CC @tbille @steverydz @jkfran

**Comment by tbille** [comment]
I am not aware if we have anything that we could link to to explain the actions

**Comment by clagom** [comment]
If we don't have the relevant doc section then we can remove the green button for now, keeping the rest

**Comment by danielmutis** [comment]
We can link to this https://juju.is/docs/working-with-actions

**Comment by tbille** [comment]
@danielmutis go on your time off.
