### ISSUE TITLE
Replace `juju deploy ...` to text explaining

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/charmhub.io#515]
From PM:  "on the charm details page instead of just saying juju deploy ambassador, it should say "try this" get any k8s, get juju and then juju deploy"

Link to tutorial: https://docs.google.com/document/d/1V6hYv6ohdCza-Md1BaL8uAHJVoWIM9bGQ75ekiTl4S4/edit

`Ready! Steady! Go!` tutorial

**Comment by danielmutis** [comment]
[Option 1](https://zpl.io/bojDj6M)
[Option 2](https://zpl.io/VKrPrQ8)

**Comment by anthonydillon** [comment]
It's the plan to give different instructions based on the platform? Microk8s is no good for none k8s change.

**Comment by clagom** [comment]
Would make sense to link to the relevant tutorial page based on the selected platform

**Comment by clagom** [comment]
I'd say option 2 gives us more room and can scale up better. it's more subtle but close to the command so should be discoverable.
