### ISSUE TITLE
Unselect 'featured' from homepage>go into charm detail>back into homepage: only 15 displayed but filter isn't selected

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/charmhub.io#567]
- Unselect 'featured' from homepage
- Go into charm detail
- Go back into homepage
- Only 15 charms displayed but filter isn't selected

_staging.charmhub.io_

**Comment by jkfran** [comment]
@steverydz this should be fixed on https://github.com/canonical-web-and-design/charmhub.io/pull/564

**Comment by steverydz** [comment]
Fixed by https://github.com/canonical-web-and-design/charmhub.io/pull/564
