### ISSUE TITLE
Configure tab: heading not in view when selected on left nav

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/charmhub.io#568]
When selecting a section/header on the left nav, you cannot see the title by default on the screen. It takes you to the start of the paragraph and not to the heading.

![Screenshot 2020-11-11 at 10.01.59.png](https://images.zenhubusercontent.com/5c73e557b33938548e4df8a3/a8b4b059-5be1-48dd-8f3a-370ff7878021)

**Comment by steverydz** [comment]
oh the joys of a fixed header :roll_eyes:

**Comment by cristinadresch** [comment]
> oh the joys of a fixed header 🙄

ah of course, the sticky header is breaking everythinggggg 🤦‍♀️

**Comment by steverydz** [comment]
@clagom @danielmutis How married are we to the sticky header? This can be fixed with JS but that really isn't ideal for what is essentially a static page, and it means we would lose the browers built-in behaviour.

**Comment by clagom** [comment]
If I remember correctly this was a specific request during one of our reviews with Mark. 
I also notice that the side navigation doesn't have active state for anchors? Is it how it's supposed to be (CC: @lyubomir-popov)? Because having the active state in the side nav would help to see where you are. 
As for the stick nav, I think the point you make is a good one, but could we remove the sticky header just in the charms detail pages and leave it in the other ones?

**Comment by steverydz** [comment]
- [ ] Fix so heading isn't hidden under sticky header
- [ ] Add "active" state to selected section

**Comment by cristinadresch** [comment]
> If I remember correctly this was a specific request during one of our reviews with Mark.
> I also notice that the side navigation doesn't have active state for anchors? Is it how it's supposed to be (CC: @lyubomir-popov)? Because having the active state in the side nav would help to see where you are.
> As for the stick nav, I think the point you make is a good one, but could we remove the sticky header just in the charms detail pages and leave it in the other ones?

The only challenge with the active state is most of the times in the configure tab you can see several sections on the screen, so should the active change on scroll automatically? and should it then always be the one at the top of the screen?

**Comment by clagom** [comment]
Yes I would say so @cristinadresch

**Comment by lyubomir-popov** [comment]
@clagom the active state can be applied to any element using `class="p-side-navigation__link is-active"`. Vanilla doesn't provide listeners to toggle the highlight on and off as you scroll if that's what you mean, as historically the framework tries to be as light on js as possible, but it doesn't discourage that either. Would it be ok to add that locally @steverydz ?

**Comment by clagom** [comment]
> @clagom the active state can be applied to any element using `class="p-side-navigation__link is-active"`. Vanilla doesn't provide listeners to toggle the highlight on and off as you scroll if that's what you mean, as historically the framework tries to be as light on js as possible, but it doesn't discourage that either. Would it be ok to add that locally @steverydz ?

Thanks @lyubomir-popov, I think UX wise makes sense, but this could be part of the modularity to be decided on product level indeed.

**Comment by steverydz** [comment]
@lyubomir-popov @clagom yeah the highlight on scroll will be local. It will be tricky due to the shortness of a lot of the sections but can be done.
