### ISSUE TITLE
Hardcoded feature list

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/charmhub.io#584]

**Comment by steverydz** [comment]
Featured charms here: https://docs.google.com/spreadsheets/d/1BTvg-NWD-yZjzN2eg-5NbTYZMXhrb5mDqqY63UxYJok/edit#gid=577595503

**Comment by anthonydillon** [comment]
@steverydz had a pass at adding the static content as I was reviewing the document. What you think?
