### ISSUE TITLE
Empty icon state for charms/bundles

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/charmhub.io#651]

**Comment by anthonydillon** [comment]
Can this be set as a default in the store DB or is it better to keep that our side so it's easier to update?

**Comment by tbille** [comment]
it is cleaner to keep this on our side, it will make it easier to update and the missing icons should be handled client side.

**Comment by spencerbygraves** [comment]
I've had a look at trying other colours such as aubergine, but that perhaps suggests Canonical involvement. I think we can stick with the existing one and close this.
