### ISSUE TITLE
Not clear how to surface "Project homepage" and "Submit a bug" links

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#709]
It's not clear to how surface the "Project homepage" or "Submit a bug" links for charms on charmhub.io. As an example, we have these set for Discourse - https://jaas.ai/u/discourse-charmers/discourse-k8s - which is being imported to https://charmhub.io/discourse but is not visible there.

This will likely need some coordination with the Snapstore team. I've spoken with @Roadmaster about this and he's expecting to need to coordinate with your team on it.

**Comment by tbille** [comment]
Ticket opened on store side:  https://bugs.launchpad.net/snapstore-server/+bug/1908069
Future import should fix this issue.
I will keep this issue open to make sure our code integrates well with the API.

**Comment by mthaddon** [comment]
I believe this should no longer be blocked. The store side bug has been marked fix released.

**Comment by mthaddon** [comment]
Erm, it seems bugs-url is included, but not homepage-url (yet).

**Comment by jkfran** [comment]
Hey @mthaddon merging Toto's PR closed automatically this issue.

On our side the website URL it's also supported, so as soon as that ticket on Launchpad is solved the websites URLs will appear.
