### ISSUE TITLE
Charms claim to be deployable at locations they're not deployable from

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#715]
As an example, on https://charmhub.io/mattermost at the top of the page it says `juju deploy cs:mattermost`, however, that will deploy https://jaas.ai/mattermost which is an IaaS charm. Per https://charmhub.io/mattermost/docs the mattermost k8s charm is deployable with `juju deploy cs:~mattermost-charmers/mattermost`.

This was highlighted by a member of the community on https://discourse.charmhub.io/t/kubernetes-examples/3928/3.

**Comment by anthonydillon** [comment]
This is correct, we need to change the deploy command to juju deploy cs:~mattermost-charmers/mattermost. Can the store return the correct deploy command?

**Comment by mthaddon** [comment]
> This is correct, we need to change the deploy command to juju deploy cs:~mattermost-charmers/mattermost. Can the store return the correct deploy command?

I don't know, you'll need to confirm with someone from the Snapstore team (not sure if you were asking me directly, but just wanted to make sure it didn't go unanswered in case you were).

**Comment by anthonydillon** [comment]
@mthaddon sorry I was replying the @tbille assigning me. But that's for the reply
