### ISSUE TITLE
https://charmhub.io/content-cache is a mix of k8s and IaaS charms

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#724]
https://charmhub.io/content-cache says "juju deploy cs:~content-cache-charmers/content-cache-k8s" (which is a kubernetes charm), but lists 20.04 LTS as a series, and is displaying the README from the IaaS charm, rather than the k8s charm.

Either the "juju deploy" line at the top should be changed, or the series and README should be changed to match.

**Comment by Roadmaster** [comment]
I've fixed this, we were importing the wrong charm which explained the inconsistencies. As requested by the powers that be, we have imported cs:~content-cache-charmers/content-cache-k8s as charmhub.io/content-cache (note the change of "promulgation" status and the slight name mangling). The instructions given for juju deploy are now consistent.

**Comment by tbille** [comment]
closing the issue.
Thanks @Roadmaster
