### ISSUE TITLE
~kubeflow-charmers/mariadb featured on front page, ~charmed-osm/mariadb-k8s should be used instead

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#743]
Per some discussions, the front page of charmhub.io currently features ~kubeflow-charmers/mariadb but ~charmed-osm/mariadb-k8s should be used instead.

The former version is obsolete according to the Kubernetes team, and the README is completely wrong (pulled in from a layer). The latter isn't yet in charmhub.io, but should be.

**Comment by Roadmaster** [comment]
Using the kubeflow-charmers one is as per the "charm prioritization" document on which we based our promulgation overrides. I'm happy to change it but would definitely welcome confirmation from product management so we don't cross the streams.

**Comment by 8ianka** [comment]
Yes I confirm! Sorry I confirmed offline first!
