### ISSUE TITLE
UX invites for brand store

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/charmhub.io#760]
UX proposal for sending / resending / revoking invites to a brand store.

**Comment by lilyvidenova** [comment]
[Here are two options](https://app.zeplin.io/project/5f3170425822f41fc299a330/dashboard?seid=5ff81b787fe91292829ee732) for viewing / resending / revoking invites to the brand store

**Comment by danielmutis** [comment]
I think the tabs are a better solution in this case. However, if the lists are not too long I wonder if we'd benefit from having both lists on the same page, as we do on dashboard.snapcraft.io

**Comment by lilyvidenova** [comment]
I don't think we have enough informaiton about how many people are usually in a brand store... but yes if there are not many users usually it would be beneficial
