### ISSUE TITLE
Configure tab does not render config.yaml properly

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/charmhub.io#761]
The whitespace in a charm's `config.yaml` file is not respected when it is rendered in HTML (on charmhub.io). This is the source text of a stanza of the [nova-compute](https://charmhub.io/nova-compute) charm:

```
  openstack-origin:                                                             
    type: string                                                                
    default: distro                                                             
    description: |
      Repository from which to install. May be one of the following:            
      distro (default), ppa:somecustom/ppa, a deb url sources entry or a        
      supported Ubuntu Cloud Archive (UCA) release pocket.                      
      .                                                                         
      Supported UCA sources include:                                            
      .                                                                         
      cloud:<series>-<openstack-release>                                        
      cloud:<series>-<openstack-release>/updates                                
      cloud:<series>-<openstack-release>/staging                                
      cloud:<series>-<openstack-release>/proposed                               
      .                                                                         
      For series=Precise we support UCA for openstack-release=                  
         * icehouse                                                             
      .                                                                         
      For series=Trusty we support UCA for openstack-release=                   
         * juno                                                                 
         * kilo                                                                 
         * ...                                                                  
      .                                                                         
      NOTE: updating this setting to a source that is known to provide          
      a later version of OpenStack will trigger a software upgrade.
```

And this is the rendered version:

![image](https://user-images.githubusercontent.com/6303808/103803462-9ab92d00-501e-11eb-98b0-668bbea69083.png)

I consider the above text illegible.

**Comment by jkfran** [comment]
Hello @pmatulis ,

Thank you for reporting the issue, just to clarify: we should respect the new lines, not related with supporting Markdown, right?

**Comment by pmatulis** [comment]
@jkfran The contents of `config.yaml` is natually YAML, not Markdown, so I'm unclear on the thrust of your question.

Generally speaking, I believe that if the YAML is valid then it should be faithfully rendered in HTML. The following aspects are not respected:

* blank lines
Blank lines are needed in order to present certain charm options (like the one in the example) in an organised way. I *thought* that including a `.` (dot) would do this but evidently not.

* newlines
Notice how newlines are ignored. This also need to be fixed.

* some characters
There may be other printable characters that are ignored but the ones that are evident in the supplied example are the `<` and `>` characters. This completely renders the text meaningless. The original store [does not do this](https://jaas.ai/nova-compute#charm-config-openstack-origin).

Thanks in advance for any support you can provide in this important matter.

**Comment by anthonydillon** [comment]
Hi Peter, the store team have taken the liberty to re-render the YAML content in a native HTML way to improve the user experience of reading the configs for all users. 

This method allows the user to consume the configs in a docs style manner. If you are familiar with the structure of the YAML, you may think it's easier to read but for people that are not. It would take time to understand the YAML construct.

If you think it would be help you, we could look into providing a link to the raw YAML file?

**Comment by pmatulis** [comment]
>  ...to improve the user experience of reading the configs for all users.

I really fail to see how what is shown in this example improves the user experience.

> If you think it would be help you, we could look into providing a link to the raw YAML file?

If we are presenting text to the user then the first thing they should see is text that is both legible (not a jumble of words devoid of whitespace) and usable (not missing any parts/characters that are critical to its understanding).

As is, the text is meaningless due to the loss of `<` and `>` characters. The disconnect here may be due to you not being familiar enough with OpenStack charms.

In terms of whitespace and organisation, do you feel the published HTML to be superior? To be clear, I don't really care about having native YAML presented (if that's even possible). I just want the whitespace to be preserved because it provides organisation to the text.

**Comment by anthonydillon** [comment]
I see you are referring to the description alone. Yes, I agree the whitespace there should be respected.

**Comment by pmatulis** [comment]
A few questions:

1. Will dots still be required to get blank lines?
2. Will the `<` and `>` characters be respected?

**Comment by jkfran** [comment]
>     1. Will dots still be required to get blank lines?
No
>     2. Will the `<` and `>` characters be respected?
Yes

You can check this change on production. Let us know if anything is wrong.

Thank you!
