### ISSUE TITLE
Display topology in bundle pages

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/charmhub.io#767]
@solazio can you document your findings in this issue so we can track our decisions.

**Comment by solazio** [comment]
- @hatched mentioned the other day that we have and svg topology available (for every bundle ?) and we could use that. For example for `kubeflow` we have this https://api.jujucharms.com/charmstore/v5/bundle/kubeflow-185/diagram.svg
- Also he setup a meeting on Monday 11/01 to discuss how I should implement the topology module, as on JAAS they are not using the data from the `bundle.yaml` file, but from some other API

**Comment by solazio** [comment]
More information can be found in this issue https://github.com/canonical-web-and-design/meeting-notes/issues/714
