### ISSUE TITLE
Update homepage loading animation

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/charmhub.io#784]
On the left, in the current image:

- icon - rounded rectangle, while the incoming icons are predominantly circles
- gradient: transitions to pure white, which makes the shape break down. My suggestion is to use two light grays, e.g. `#f7f7f7` and `#e5e5e5`
- the gradient should ideally be over all shapes, not individual. I think that's feasible, let me know if you want me to find an example css implementation. The last image (the black gradient) illustrates how the top left to bottom-right gradient is relative to the top /bottom of the skeleton blocks as a whole, not individually:
- overall rectangle shape is truer to the font metrics. although not ideal. For an ideal one check out [this example](https://codepen.io/tylersticka/pen/PmRRqb?editors=1100) using an open source typeface named "redacted".

![image](https://user-images.githubusercontent.com/2741678/104479365-4502f880-55bb-11eb-8cda-cf06171a49cb.png)

(The third image from the left is my actual proposal), unless we go with the redacted font, which will look slightly nicer.)

**Comment by lyubomir-popov** [comment]
updated to include image and some of the formatting
