### ISSUE TITLE
[Discourse] Navigation hearder bar on scroll doesn't have negative logo and text is black on black

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/charmhub.io#792]
Example:
![Screenshot 2021-01-20 at 14.32.42.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/204b1cfb-f239-400c-8109-978172a06009)

**Comment by anthonydillon** [comment]
Strange, I can't seem to replicate this. Could you share a link and browser to help replicate?

**Comment by clagom** [comment]
Sorry @anthonydillon, it was just cache. Hard refresh did the trick.
