### ISSUE TITLE
https://charmhub.io/mongodb-k8s (which is featured on the front page) has "no readme available"

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#818]
As the subject says https://charmhub.io/mongodb-k8s (which is featured on the front page) has "no readme available". https://jaas.ai/u/charmed-osm/mongodb-k8s/29 (which is what the page is based on) has a README.

**Comment by Roadmaster** [comment]
This issue can be closed, we've fixed this (another victim of the importer accident mentioned in https://github.com/canonical-web-and-design/charmhub.io/issues/801)
