### ISSUE TITLE
graylog HA functionality update

### ISSUE THREAD

**Issue by rgrullon** [canonical-web-and-design/charmhub.io#847]
Based on current architecture, graylog can run in HA mode. Can the section on scale out be updated with more details on how this functions?

https://charmhub.io/graylog

**Comment by hatched** [comment]
Hi @rgrullon this is actually the issue tracker for the charmhub.io website itself.

For issues with the charms you'll want to file them directly with the charm author. In this case, that would be https://bugs.launchpad.net/charm-graylog
