### ISSUE TITLE
Code and text rendered the same way

### ISSUE THREAD

**Issue by edumucelli** [canonical-web-and-design/charmhub.io#856]
[This](https://charmhub.io/postgresql/configure#extra_pg_conf) configuration item should be rendered as code or, at least, have a clear separation to show this is [preformatted multi-line block](https://github.com/fletcher/MultiMarkdown/blob/master/Documentation/Markdown%20Syntax.md#preformatted-code-blocks) and not as normal text.

Current display is difficult to read. I wanted to copy this default configuration, but in the current form cloning the repository in question is a must to avoid copy/pasting errors. For reference [here](https://git.launchpad.net/postgresql-charm/tree/config.yaml#n44) is the source of this parameter.

![extra_pg_conf](https://user-images.githubusercontent.com/959623/110468135-cb295000-80cf-11eb-9621-1f898b7182d0.png)

**Comment by jkfran** [comment]
I think we should fix it in the same way we fixed the description on issue https://github.com/canonical-web-and-design/charmhub.io/issues/761
