### ISSUE TITLE
Keep empty state when no published charms

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/charmhub.io#863]
When the user has no published charms display, keep the empty state page.

See snapcraft as an example:

![image.png](https://images.zenhubusercontent.com/583afafbb9dc3c6220228d0c/e8f3fbe9-3586-49f6-8b86-a9189f1955f6)

**Comment by solazio** [comment]
@danielmutis when the user has registered charms/bundles but has no published charms/bundles,
do we want something like:
![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/844bcc43-c2ce-4a75-b226-8a7921083732)

or like:
![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/b8ae2bdd-5de3-454d-b335-4df5e749ae57)

**Comment by danielmutis** [comment]
@solazio this sounds good. Let's go for what you are proposing in example 1. A third option could be to keep the 3-column info section under the registered names table, until they publish something.
