### ISSUE TITLE
500 embeddeble card for name registered but not published

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/charmhub.io#864]
- Register a new name
- Go on the `https://charmhub.io/CHARMNAME/publicise/cards`
- see the card 500

**Comment by danielmutis** [comment]
<img width="1633" alt="Screenshot 2021-03-24 at 12 06 48" src="https://user-images.githubusercontent.com/59825615/112307943-77a32e80-8c99-11eb-839c-8ef1b953d772.png">
We can display a message like this on here that reads:

### "Here you will find ways of sharing your charm/bundle"
"This section will only be available once you have published your charm/bundle"
CTA: Learn how to publish an operator
