### ISSUE TITLE
Can't update site if summary empty

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/charmhub.io#869]
- Have a charm with no summary.
- update the site 
- press save button
- Blocked because of "Field required on summary"

**Comment by solazio** [comment]
@tbille @danielmutis on snapcraft.io we have "title" and "summary" marked as `reuired`, which means the user cannot save empty title or summary,  hence the same behaviour is replicated on charmhub.

Related to the title, @danielmutis was suggesting to use either the "title" or the "name" from the metadata, but @tbille would like to use "title" or blank. What would make more sense?

**Comment by danielmutis** [comment]
I think given that they can publish their charm from the CLI, without ever going into the UI, we need to have a backup for when a charmer hasn't filled in this in their metadata. I think it would be more desirable to use the charm name, than to have a charm with a blank name. They can both be required in the UI, but I think having no summary is more tolerable than having no name.

**Comment by solazio** [comment]
Agreed with Daniel to keep the current behaviour:
- Title - if there is no title we display empty string; the title field is required in order to submit the form.
- Summary - if there is no summary we display empty string; the summary field is required as well.

Closing
