### ISSUE TITLE
Icons on top of tooltip on librairies page

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/charmhub.io#881]
![image.png](https://images.zenhubusercontent.com/583afafbb9dc3c6220228d0c/624d65a8-12b5-41ac-a200-87bb17708931)

**Comment by spencerbygraves** [comment]
@tbille can we also check the line height is correct please, it looks a bit tight. Thanks.

**Comment by solazio** [comment]
@spencerbygraves the line-height is 1rem, same as we have https://vanillaframework.io/docs/patterns/tooltips
