### ISSUE TITLE
Searching for postgresql-k8s doesn't find postgresql-k8s

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#910]
https://charmhub.io/?q=postgresql-k8s gives no results, but https://charmhub.io/postgresql-k8s exists.

**Comment by Roadmaster** [comment]
Looks like a charmhub API-side thing: curl http://api.charmhub.io/v2/charms/find?q=postgresql-k8s | jq

**Comment by tbille** [comment]
@Roadmaster just opened an issue for this https://bugs.launchpad.net/snapstore-server/+bug/1922658

**Comment by tbille** [comment]
It seems this is fixed now.
Closing the issue.
