### ISSUE TITLE
Deployment instruction line in page header is incorrect

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#925]
Taking https://charmhub.io/postgresql-charmers-postgresql-k8s as an example, it says `juju deploy cs:postgresql-charmers-postgresql-k8s`.  However:
```
mthaddon@tenaya:~$ juju deploy cs:postgresql-charmers-postgresql-k8s
ERROR cannot resolve URL "cs:postgresql-charmers-postgresql-k8s": charm or bundle not found
mthaddon@tenaya:~$ juju deploy postgresql-charmers-postgresql-k8s
Located charm "postgresql-charmers-postgresql-k8s" in charm-hub, revision 11
Deploying "postgresql-charmers-postgresql-k8s" from charm-hub charm "postgresql-charmers-postgresql-k8s", revision 11 in channel stable
```
Note that `juju deploy cs:~postgresql-charmers/postgresql-k8s` does also work.

**Comment by mthaddon** [comment]
As a follow up to this, I've just published https://charmhub.io/postgresql-k8s using charmcraft, and it shows `juju deploy cs:~postgresql-charmers/postgresql-k8s` as well, but should show `juju deploy postgresql-k8s`. That command currently fails, but I'll troubleshoot that with Daniel.

**Comment by tbille** [comment]
The `cs:` is now removed and we have a notification on the charm pages with a warning to use juju 2.9. Closing this issue.
