### ISSUE TITLE
Charm description text is cut off on cards

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/charmhub.io#963]
To reproduce visit charmhub.io at a resolution of 1680w in FF.

<img width="220" alt="Screen Shot 2021-04-28 at 10 01 51 AM" src="https://user-images.githubusercontent.com/532033/116435931-1ecf3480-a809-11eb-9939-4980e77a19a1.png">

**Comment by steverydz** [comment]
This doesn't seem to be an issue anymore so closing.
