### ISSUE TITLE
Uploaded charm not searchable

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#964]
I've uploaded a charm to charmhub (https://charmhub.io/nginx-ingress-integrator) but if I search for "nginx" it doesn't show up https://charmhub.io/?q=nginx. What do I need to do to make it searchable? It's going to be mentioned in the kubecon demo so it'd be good to make sure it's searchable in case people who attend that are later looking for it.

**Comment by tbille** [comment]
This should be fixed now.
By default new charms are unlisted.
Closing this issue
