### ISSUE TITLE
Font weight on discourse too low

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/charmhub.io#977]
It looks like the font-weight was reduced to 100 which, with grey text on a white background, is quite hard to read.

<img width="659" alt="Screen Shot 2021-04-30 at 11 08 28 AM" src="https://user-images.githubusercontent.com/532033/116729526-7fdf3f80-a9a4-11eb-9411-9ce9d7863584.png">

**Comment by solazio** [comment]
This was fixed in https://github.com/canonical-web-and-design/discourse-nav/issues/5.
