### ISSUE TITLE
Message explaining Juju 2.9 is required is a little alarming

### ISSUE THREAD

**Issue by jnsgruk** [canonical-web-and-design/charmhub.io#998]
Some feedback from a sidecar charm campaign meeting today, was that the banner we display explaining that Juju 2.9 is required makes it look a little too "alarming". Can we find a an alternative way of indicating the Juju 2.9 requirement, especially now it's released into stable?
![Screenshot-20210510100731-1204x447](https://user-images.githubusercontent.com/668505/117640794-4e712b80-b17d-11eb-85cc-46488247075f.png)

**Comment by tbille** [comment]
We should have a UX/Visual review of this section.

**Comment by jkfran** [comment]
It should be replaced with information icon

**Comment by Lukewh** [comment]
This seems to have been addressed, but this issue was lost along the way. Closing it :)!
